### ISSUE TITLE
Output file formats for TRiCoLor tutorial  

### ISSUE THREAD

**Issue by lauragails** [davidebolo1993/TRiCoLOR#15]
Hello, 
It seems like step2  is expecting filtered output from step 1. When I feed in the output 

**Step 1**: works fine
`TRiCoLOR SENSoR -bam son/sim.srt.bam -o sensor_son`

**Step 2**: From tutorial, does not work because ".filtrd" is missing from output from step 1 
TRiCoLOR REFER -g GRCh38_full_analysis_set_plus_decoy_hla.fa -bam son/sim.srt.bam -bed sensor_son/TRiCoLOR.srt.fltrd.bed -o refer_son -s 20 --samplename SON

**Step 2** (after converting TRiCoLOR.srt.bed.gz to TRiCoLOR.srt.bed)
TRiCoLOR REFER -g GRCh38_full_analysis_set_plus_decoy_hla.fa -bam son/sim.srt.bam -bed sensor_son/TRiCoLOR.srt.bed -o refer_son -s 20 --samplename SON

Error: 
```
TRiCoLOR REFER v1.1
[17/01/2023 17:15:39][Message] Using RegEx (.+?)\1{4,}
[17/01/2023 17:15:39][Message] Processing chromosome chr20
[17/01/2023 17:15:40][Message] Creating .mmi index for current chromosome
Traceback (most recent call last):
  File "/hpc/packages/minerva-centos7/py_packages/3.7/bin/TRiCoLOR", line 33, in <module>
    sys.exit(load_entry_point('TRiCoLOR==1.1.0', 'console_scripts', 'TRiCoLOR')())
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/TRiCoLOR-1.1.0-py3.7.egg/TRiCoLOR/TRiCoLOR.py", line 194, in main
    args.func(parser, args)
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/TRiCoLOR-1.1.0-py3.7.egg/TRiCoLOR/TRiCoLOR.py", line 280, in run_subtool
    submodule.run(parser,args)
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/TRiCoLOR-1.1.0-py3.7.egg/TRiCoLOR/REFER/REFER.py", line 671, in run
    c.aligner=mp.Aligner(os.path.abspath(gendir + '/' + b_chrom + '.fa'),fn_idx_out=chromind, preset='asm10') #standard present for consensus-to-ref alignment
  File "python/mappy.pyx", line 145, in mappy.Aligner.__cinit__
TypeError: expected bytes, str found
```

Do you know what is happening/what I am doing wrong? Thank you!

**Comment by davidebolo1993** [comment]
Hey @lauragails,

thanks for being in touch. I haven't see this happening, but I'll try to replicate. I'm swamped with many other things these days, I may be slow in getting back. Talk to you asap.

Best,

Davide

**Comment by lauragails** [comment]
Understood - thank you for trying!

**Comment by lauragails** [comment]
FYI I did get it to work when I pulled the container with singularity and used like this (in case anyone hits the same thing): 

```
singularity pull docker://davidebolo1993/tricolor
singularity run /path/to/tricolor_latest.sif TRiCoLOR REFER -g $REF -bam $proband -bed $OUTDIR/sensor_${bname_proband}/TRiCoLOR.srt.bed -o $OUTDIR/refer_${bname_proband} -s 20 --samplename $bname_proband
```

It's too soon to tell if I'll get results, but I'm optimistic! I suspect this has to do with a python 2/3 conversion under the hood: 
https://github.com/davidebolo1993/TRiCoLOR/assets/7000365/c393d9f0-af33-4dcd-a546-c6d0e701c5a8

Initially I had our HPC install the software in their packages folder, which sometimes has/makes conflicts 

Thank you, Davide!

**Comment by davidebolo1993** [comment]
Hey @lauragails, thanks for reporting and sorry for not being able to properly follow-up on this. You should have further issues, feel free to get in touch in a new issues.

Thanks,

Davide
