### ISSUE TITLE
Merge bed files from TRiCoLOR SENSoR

### ISSUE THREAD

**Issue by wdecoster** [davidebolo1993/TRiCoLOR#2]
Hi,

Do you have any recommendations on, when running on multiple samples, if we should merge bed files from each SENSoR result and use the merged bed file for the subsequent REFER step? If so, how would you recommend to do the merging? Or would it be best to run each sample with their own SENSoR bed only?

Thanks,
Wouter

**Comment by davidebolo1993** [comment]
Hi @wouter, 

unless these multiple samples are actually multiple runs from the same sample (but in that case it makes more sense to merge aligned BAM files before) or you are interested in investigating specific repetitive regions across all the samples (but in that case you can provide your own BED to SENSoR, in standard format), I would say that running REFER using the corresponding BED from SENSoR is the way to go.

Best,

Davide

**Comment by wdecoster** [comment]
Those are different samples. Alright, thanks for the quick reply!
