### ISSUE TITLE
TRiCoLOR SENSoR failed in creating bed file

### ISSUE THREAD

**Issue by Nehir291** [davidebolo1993/TRiCoLOR#8]
Hi,
I just started to use TRiCoLOR on a Pacbio HiFi CCS sample (NA19240), however I could not make TRiCoLOR SENSoR worked on this bam file. After processsing all the chromosomes, it fails in creating bed file for the repeat intervals. I was working with the latest docker image (davidebolo1993/tricolor:latest). Do you have any idea what could be the cause? Many thanks 

[09/07/2021 15:31:12][Message] Processing chromosome chrUn_GL000218v1
[09/07/2021 15:31:12][Message] Processing chromosome chrEBV
[09/07/2021 15:31:15][Message] Writing intervals to BED
Traceback (most recent call last):
  File "/miniconda/envs/tricolorenv/bin/TRiCoLOR", line 33, in <module>
    sys.exit(load_entry_point('TRiCoLOR==1.1.0', 'console_scripts', 'TRiCoLOR')())
  File "/miniconda/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/TRiCoLOR.py", line 194, in main
    args.func(parser, args)
  File "/miniconda/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/TRiCoLOR.py", line 280, in run_subtool
    submodule.run(parser,args)
  File "/miniconda/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/SENSoR/SENSoR.py", line 449, in run
    bedfile=pybedtools.BedTool(os.path.abspath(c.OUT + '/H1.bed'))
  File "/miniconda/envs/tricolorenv/lib/python3.8/site-packages/pybedtools-0.8.2-py3.8-linux-x86_64.egg/pybedtools/bedtool.py", line 522, in __init__
    raise FileNotFoundError(msg)
FileNotFoundError: File "/PHShome/enk15/TRiCoLOR/TRiCoLOR/sensor_NA19240/H1.bed" does not exist

**Comment by davidebolo1993** [comment]
Hi @Nehir291,

it seems that the BED for haplotype 1 has not been created. This can be either a problem with the phasing step (the input BAM must be phased before SENSoR) or with the number of regions being identified as low-entropy (no regions, in this case). Sharing your dataset would be useful for debugging.

Thanks,

Davide

**Comment by Nehir291** [comment]
Dear Davide,

Thank you for the quick feedback. As you pointed above, the problem was the lack of haplotype-tags on the bam files. I will follow your script on my data and hope that it will work: https://github.com/davidebolo1993/TRiCoLOR/blob/master/paper/data/prepare.sh

**Comment by davidebolo1993** [comment]
Hi @Nehir291,

I don't know if this is appropriate for CCS, but for CLR data I usually use [Longshot](https://github.com/pjedge/longshot) for phasing. 

Best,

Davide

**Comment by Nehir291** [comment]
Hi @davidebolo1993
Thanks for the suggestion, I will try it!
bests,
Nehir

**Comment by davidebolo1993** [comment]
Hi @Nehir291,

any updates on this?

Best,

Davide

**Comment by Nehir291** [comment]
Hi @davidebolo1993,

Thank you for your interest. The software worked with pacbio CCS reads that are phased by longshot phased vcfs, whatshap phased vcfs or strandseq/StrandPhaseR phased vcfs. However, I encounter another problem. The output of sensor analysis, despite revealing a lot of candidate region for STR repeats, does not cover all the disease associated STR genes (daSTR). I tried many times with the bam phased by different methods, however I got only the half of 65 daSTRs covered by the output of Sensor module. When i bypass sensor and use refer module with a bed file covering these daSTRs, I got only few of them genotyped (in some trials 4 out of 65 STRs). I dont know whether the limitation is rooted by the phasing or the software. Do you have any suggestion on how I can force the software to give an output for the regions of interest?

**Comment by davidebolo1993** [comment]
This really seems to depend on the number of reads per haplotype after phasing (btw, what is the original coverage for those daSTRs?). Phasing is great, but unassigned reads sometimes complicate stuff because they can lower coverage a lot. If the repetitive motifs are known and coverage is sufficiently high we can give [TREADMILL](https://github.com/davidebolo1993/TREADMILL) a try on these, as this tool does not require previous phasing information and genotyping is performed via ML/clustering. Let me know if this is of interest.

Best, 

Davide

**Comment by Nehir291** [comment]
The average coverage of the daSTRs before phasing is around 28, all the sites are above 10x.Probably as you said after phasing, the coverage may drop (i did not check that).  Yes I would like to try https://davidebolo1993.github.io/treadmilldoc/

**Comment by davidebolo1993** [comment]
TREADMILL is tested with nanopore data, but in principle should work with pacbio targets. Get in touch with me at davidebolognini7@gmail.com, so that we can try to set up a pipeline for your case.

I'm closing this issue for the time being,

Davide
