### ISSUE TITLE
Question about using TRiCoLOR for VNTR profiling

### ISSUE THREAD

**Issue by FangfeiHu** [davidebolo1993/TRiCoLOR#9]
Hi David,

I found in the discussion part of your paper that TRiCoLOR might be used for VNTR (motifs >6 bp). Follow the help document, I tried it using a targeted Cas9 ONT sequencing data. But there is nothing in the result BED files after running the REFER program. I'm afraid this is caused by my wrong command. Could you help me check with it?

The command is :
`TRiCoLOR REFER -mm 50 -g data_for_tricolor/chr1.fa -bam data_for_tricolor/20191118_Cas9_Barcoding_barcode06_pass_haplotagged.bam -bed data_for_tricolor/sensor_cas9/TRiCoLOR.srt.fltrd.bed -o target1_1`

I set the maximum motif size to 50 bp because the golden standard for the length of the repeat unit is 42.

Waiting for your reply.

Kind regards,
Fangfei

**Comment by davidebolo1993** [comment]
Hi @FangfeiHu, 

this really looks like an hard task for TRiCoLOR. Maybe we can give [TREADMILL](https://github.com/davidebolo1993/TREADMILL) a try. If you are interested, get in touch at davidebolognini7@gmail.com and we can try to sort this out.

Thanks,

Davide
